-- Traduce el EN/DE de las 3 fichas piloto para que coincidan con la nueva
-- descripcion en ES. Sin clave 'es': LocalText usa i18n[locale] || value, y
-- si hubiera clave 'es' aqui taparia el campo base en español (el mismo bug
-- que ya se arreglo para bio de DJs).

update public.clubs set description_i18n = jsonb_build_object(
  'en', 'La Santa Benicàssim is the go-to open-air club on Spain''s Costa del Azahar, right on the N-340 road (Km 78), at the entrance to Benicàssim and just minutes from Castellón de la Plana. Its spacious terrace features two bars and a central dance floor surrounded by palm trees and tropical-style lighting, while an indoor room keeps the venue open year-round, beyond the summer season. The music moves from reggaeton and urban hits to techno, acid techno, tech house and afro house sets, making it one of the few clubs in the area that brings both crowds together on the same night.',
  'de', 'La Santa Benicàssim ist der bekannteste Open-Air-Club an der Costa del Azahar, direkt an der N-340 (Km 78), am Ortseingang von Benicàssim und nur wenige Minuten von Castellón de la Plana entfernt. Die großzügige Terrasse verfügt über zwei Bars und eine zentrale Tanzfläche, umgeben von Palmen und tropischer Beleuchtung, während ein Innenbereich den Club auch außerhalb der Sommersaison das ganze Jahr über geöffnet hält. Musikalisch reicht das Spektrum von Reggaeton und urbanen Hits bis zu Techno-, Acid-Techno-, Tech-House- und Afro-House-Sets – einer der wenigen Clubs der Region, der beide Publikumsgruppen in derselben Nacht zusammenbringt.'
) where id = '10833c27-b40a-4070-8144-425de255fbd2'; -- LA SANTA

update public.clubs set description_i18n = jsonb_build_object(
  'en', 'Right in the heart of the Magaluf Strip, on Avinguda de l''Olivera, Panama Jack is one of the liveliest clubs in Mallorca''s main tourist strip. The line-up focuses on reggaeton, Latin music and global hits, with international DJs playing the biggest tracks of the moment alongside a show of lights and CO2 cannons. It sits just a few metres from BCM Mallorca on the same avenue, making it a regular stop for anyone doing a club crawl along the Strip without leaving the block.',
  'de', 'Mitten im Herzen des Magaluf Strip, an der Avinguda de l''Olivera, ist Panama Jack einer der angesagtesten Clubs im touristischen Zentrum Mallorcas. Das musikalische Konzept setzt auf Reggaeton, lateinamerikanische Musik und globale Hits, aufgelegt von internationalen DJs, begleitet von Lichtshows und CO2-Kanonen. Der Club liegt nur wenige Meter vom BCM Mallorca entfernt, in derselben Avenue, und ist damit ein fester Stopp für alle, die entlang des Strips von Club zu Club ziehen, ohne den Straßenzug zu verlassen.'
) where id = 'd565474b-004e-4485-a8b9-0221b56521b8'; -- PANAMA JACK MAGALUF

update public.clubs set description_i18n = jsonb_build_object(
  'en', 'Perro Negro Madrid is the capital''s outpost of the Medellín club that became an international reference for perreo, at number 28 Calle Don Ramón de la Cruz, in the heart of the Salamanca district. The venue plays no-holds-barred classic and current reggaeton alongside trap, dembow, dancehall and guayeteo, in a dark, unpretentious atmosphere that channels the spirit of the original Colombian venue. VIP tables and its proximity to other Salamanca clubs — Rubicon, Terraza Karau, Gunilla Club and Sala de Despecho are all a short walk away — make it a regular stop for anyone doing a night out around the neighbourhood.',
  'de', 'Perro Negro Madrid ist der Ableger des Clubs aus Medellín in der spanischen Hauptstadt, der international zur Referenz für Perreo wurde, in der Calle Don Ramón de la Cruz 28, mitten im Stadtviertel Salamanca. Der Club setzt kompromisslos auf klassischen und aktuellen Reggaeton sowie Trap, Dembow, Dancehall und Guayeteo, in einer dunklen, unprätentiösen Atmosphäre, die den Geist des kolumbianischen Originals widerspiegelt. VIP-Bereiche und die Nähe zu anderen Clubs in Salamanca – Rubicon, Terraza Karau, Gunilla Club und Sala de Despecho liegen alle nur einen kurzen Spaziergang entfernt – machen ihn zu einem festen Stopp für alle, die die Gegend nachts erkunden.'
) where id = 'f63827b6-6e44-48eb-b08f-41258518abeb'; -- PERRO NEGRO MADRID
