-- Reescritura de bio (ES/EN/DE) para los 2 DJs con mas impresiones en Search
-- Console sin apenas clics: SAIKO (356 impr) y BUNT. (121 impr). Ambos tienen
-- paso real por Mallorca en la base de datos (SAIKO x FITZ en FITZ MALLORCA,
-- BUNT en AMOK MALLORCA), pero la bio actual era un texto tipo Wikipedia sin
-- esa conexion, que es justo lo que la gente busca con "saiko mallorca" /
-- "bunt mallorca". Se actualizan bio y bio_i18n a la vez (los 3 idiomas), asi
-- que no queda ninguna clave desincronizada tapando el cambio.

update public.djs set
  bio = 'Saiko, cuyo nombre real es Miguel Cantos Gómez, es un cantante, compositor y productor nacido en Armilla, Granada, que ha llevado su fusión de reguetón, trap y música urbana a algunas de las noches más comentadas de Mallorca, como la sesión SAIKO x FITZ en FITZ MALLORCA. Desde temprana edad mostró una fuerte inclinación por la música urbana, destacando rápidamente en la escena española por su versatilidad para fusionar el reguetón clásico con el trap y matices de pop synth y música electrónica. A través de grandes éxitos de ventas y colaboraciones internacionales de primer nivel, Saiko se ha consolidado como un auténtico fenómeno de masas y un habitual de la noche mallorquina cuando pisa la isla.',
  bio_i18n = jsonb_build_object(
    'es', 'Saiko, cuyo nombre real es Miguel Cantos Gómez, es un cantante, compositor y productor nacido en Armilla, Granada, que ha llevado su fusión de reguetón, trap y música urbana a algunas de las noches más comentadas de Mallorca, como la sesión SAIKO x FITZ en FITZ MALLORCA. Desde temprana edad mostró una fuerte inclinación por la música urbana, destacando rápidamente en la escena española por su versatilidad para fusionar el reguetón clásico con el trap y matices de pop synth y música electrónica. A través de grandes éxitos de ventas y colaboraciones internacionales de primer nivel, Saiko se ha consolidado como un auténtico fenómeno de masas y un habitual de la noche mallorquina cuando pisa la isla.',
    'en', 'Saiko, whose real name is Miguel Cantos Gómez, is a singer, songwriter and producer born in Armilla, Granada, who has brought his fusion of reggaeton, trap and urban music to some of Mallorca''s most talked-about nights, including the SAIKO x FITZ session at FITZ MALLORCA. From an early age he showed a strong passion for urban music, quickly gaining prominence in the Spanish scene thanks to his ability to blend classic reggaeton with trap and touches of synth-pop and electronic music. Through major chart-topping hits and top-tier international collaborations, Saiko has established himself as a true mainstream phenomenon and a regular on Mallorca''s nightlife whenever he plays on the island.',
    'de', 'Saiko, bürgerlich Miguel Cantos Gómez, ist ein Sänger, Songwriter und Produzent aus Armilla, Granada, der seine Mischung aus Reggaeton, Trap und Urban Music zu einigen der meistdiskutierten Nächte Mallorcas gebracht hat, darunter die Session SAIKO x FITZ im FITZ MALLORCA. Schon in jungen Jahren zeigte er ein großes Talent für Urban Music und entwickelte sich schnell zu einer festen Größe in der spanischen Szene, da er klassisches Reggaeton gekonnt mit Trap sowie Synth-Pop- und Elektronik-Elementen verbindet. Durch weltweite Chart-Erfolge und hochkarätige internationale Kollaborationen hat sich Saiko zu einem absoluten Massenphänomen entwickelt und zu einem festen Namen im Nachtleben Mallorcas, sobald er auf der Insel auflegt.'
  )
where id = 'c558c380-440a-404b-af78-416c94a73434'; -- SAIKO

update public.djs set
  bio = 'BUNT. es el proyecto musical del DJ y productor alemán Levi Wijk, conocido internacionalmente por popularizar el sonido "stutter house", que ha traído su directo a Mallorca con la fiesta Amøk x Crush en AMOK MALLORCA. Con lanzamientos virales y millones de reproducciones en Spotify y SoundCloud, se ha situado como un referente innovador en la música electrónica global. Su dinamismo en el escenario y su estética colorida le han llevado a girar por las principales capitales europeas y norteamericanas, y su paso por la isla lo confirma como uno de los nombres internacionales que ya ha pinchado en los clubs mallorquines.',
  bio_i18n = jsonb_build_object(
    'es', 'BUNT. es el proyecto musical del DJ y productor alemán Levi Wijk, conocido internacionalmente por popularizar el sonido "stutter house", que ha traído su directo a Mallorca con la fiesta Amøk x Crush en AMOK MALLORCA. Con lanzamientos virales y millones de reproducciones en Spotify y SoundCloud, se ha situado como un referente innovador en la música electrónica global. Su dinamismo en el escenario y su estética colorida le han llevado a girar por las principales capitales europeas y norteamericanas, y su paso por la isla lo confirma como uno de los nombres internacionales que ya ha pinchado en los clubs mallorquines.',
    'en', 'BUNT. is the musical project of German DJ and producer Levi Wijk, globally recognized for pioneering the ''stutter house'' sound, who brought his live set to Mallorca with the Amøk x Crush party at AMOK MALLORCA. With viral hits and millions of streams across Spotify and SoundCloud, he has established himself as an innovative force in dance music. His vibrant stage presence and uplifting productions have taken him to major European and American clubs, and his time on the island confirms him as one of the international names who has already played Mallorca''s clubs.',
    'de', 'BUNT. ist das Musikprojekt des deutschen DJs und Produzenten Levi Wijk, der weltweit als Wegbereiter des ''Stutter House''-Sounds bekannt ist und mit der Party Amøk x Crush im AMOK MALLORCA auch auf Mallorca aufgelegt hat. Mit viralen Hits und Millionen von Streams auf Spotify und SoundCloud hat er sich als innovative Kraft in der elektronischen Musik etabliert. Seine mitreißende Bühnenpräsenz und sein farbenfroher Sound haben ihn in die großen Clubs Europas und Nordamerikas geführt, und sein Auftritt auf der Insel bestätigt ihn als einen der internationalen Namen, die bereits in Mallorcas Clubs aufgelegt haben.'
  )
where id = 'e9d37d2d-6b55-4b5c-9961-2d729ff62710'; -- BUNT.
