-- Traducciones EN/DE (description_i18n) para los clubs de la expansion a Ibiza,
-- Palma, Barcelona, Sevilla, Bilbao y Malaga. Redactadas pensando en las busquedas
-- de esos idiomas ("nightclub in Ibiza", "Diskothek Palma", etc.), no como traduccion
-- literal del texto en castellano.
-- Ejecutar en el SQL Editor de Supabase (una sola vez).

update public.clubs set description_i18n = jsonb_build_object('en', 'Beachfront bar on Málaga''s promenade with a terrace over the harbour. A go-to nightlife spot with Latin, pop and electronic music and sea views.', 'de', 'Strandbar an der Promenade von Málaga mit Terrasse und Hafenblick. Beliebter Nachtleben-Treffpunkt mit Latin, Pop und elektronischer Musik.') where id = '7b27ec01-84af-4258-88bc-9ff1d28719a6'; -- Mala Compañía Málaga
update public.clubs set description_i18n = jsonb_build_object('en', 'Bar and club in Bilbao''s old town (Casco Viejo). An alternative nightlife spot with a warm atmosphere and a mix of indie, electronic and pop music.', 'de', 'Bar und Club in der Altstadt von Bilbao (Casco Viejo). Alternativer Ort im Nachtleben mit warmer Atmosphäre und einem Mix aus Indie, Electronic und Pop.') where id = 'aaf45e61-a061-4db7-ac3f-1486df081576'; -- El Sótano Bilbao
update public.clubs set description_i18n = jsonb_build_object('en', 'Upscale nightclub on Barceloneta beach with sea views. One of Barcelona''s landmark clubs, holding several thousand guests for high-end nights out.', 'de', 'Edler Nachtclub am Strand von Barceloneta mit Meerblick. Einer der bekanntesten Clubs Barcelonas mit Platz für mehrere Tausend Gäste.') where id = 'd6934e57-6b4a-4348-97e7-f5643f6ddf89'; -- Opium Barcelona
update public.clubs set description_i18n = jsonb_build_object('en', 'Beach club and nightclub on El Palo beach in Málaga. A beach bar by day that turns into a summer party by night, typical of Málaga''s coastal nightlife.', 'de', 'Beach Club und Diskothek am Strand von El Palo in Málaga. Tagsüber Strandbar, abends Sommerparty, typisch für das Nachtleben an Málagas Küste.') where id = 'a0cb688c-59c7-46ac-84a3-4fec9be935b5'; -- Booga Beach Málaga
update public.clubs set description_i18n = jsonb_build_object('en', 'Upscale beach club in Pedregalejo, Málaga, overlooking the Mediterranean. A summer nightlife landmark blending daytime beach lounging with clubbing after dark.', 'de', 'Exklusiver Beach Club in Pedregalejo, Málaga, mit Blick aufs Mittelmeer. Kombiniert tagsüber Strandflair mit Clubbing am Abend.') where id = 'a16b1ae5-eba5-4be9-b473-8b843355f04d'; -- Purobeach Málaga
update public.clubs set description_i18n = jsonb_build_object('en', 'Ultra-club on Playa d''en Bossa with cutting-edge sound and visuals. One of Ibiza''s flagship high-end nightclubs, hosting residencies from world-renowned DJs.', 'de', 'Ultra-Club an der Playa den Bossa mit modernster Sound- und Lichttechnik. Einer der führenden High-End-Clubs auf Ibiza mit Residencies internationaler DJs.') where id = '8b2594a2-62a3-47cd-a5c5-fc43ff711da2'; -- Hï Ibiza
update public.clubs set description_i18n = jsonb_build_object('en', 'Live music venue and club on the Triana promenade in Seville. A stage for live shows, flamenco fusion and alternative Andalusian acts.', 'de', 'Konzertsaal und Club an der Promenade von Triana in Sevilla. Bühne für Live-Musik, Flamenco-Fusion und alternative andalusische Künstler.') where id = '3d391528-ba8c-459a-bb4e-015cd749adc0'; -- Eslabón Sevilla
update public.clubs set description_i18n = jsonb_build_object('en', 'Iconic sunset bar in Cala Conta, Ibiza. Legendary for its chill-out sunsets that turn into a summer night party as the sun goes down.', 'de', 'Ikonische Sunset-Bar in Cala Conta, Ibiza. Berühmt für den Chill-out-Sonnenuntergang, der abends in eine Sommerparty übergeht.') where id = 'c46f620b-c3be-4998-91d9-9158be7288f1'; -- Café del Mar
update public.clubs set description_i18n = jsonb_build_object('en', 'Legendary Ibiza nightclub and symbol of Balearic nightlife. A world-famous name in electronic music, with international artists and a cosmopolitan crowd.', 'de', 'Legendärer Nachtclub auf Ibiza und Symbol des balearischen Nachtlebens. Weltberühmt für elektronische Musik mit internationalen Künstlern und kosmopolitischem Publikum.') where id = 'a4c4d118-0886-4639-8869-728b54a3a3fb'; -- Pacha Ibiza
update public.clubs set description_i18n = jsonb_build_object('en', 'Bar and club in the historic centre of Palma de Mallorca. An alternative nightlife spot with varied music and a mixed crowd.', 'de', 'Bar und Club in der Altstadt von Palma de Mallorca. Alternativer Ort im Nachtleben mit vielseitiger Musik und gemischtem Publikum.') where id = 'fc2e7c07-ed0b-4b29-806d-ded643028ce0'; -- Garito Café
update public.clubs set description_i18n = jsonb_build_object('en', 'Club specialising in salsa and Latin music in central Málaga. A lively nightlife venue with a festive vibe and a multicultural crowd.', 'de', 'Auf Salsa und Latin-Musik spezialisierter Club im Zentrum von Málaga. Lebendiger Ort mit festlicher Stimmung und multikulturellem Publikum.') where id = 'ce10d89f-9f3c-40ee-82d5-859aa86902d4'; -- Salsa Latina Málaga
update public.clubs set description_i18n = jsonb_build_object('en', 'Multi-room club and concert complex in Poblenou, a landmark of Barcelona''s nightlife with several stages covering rock, indie and electronic.', 'de', 'Club- und Konzertkomplex mit mehreren Sälen in Poblenou, ein Wahrzeichen des Barceloneser Nachtlebens mit Rock, Indie und Electronic.') where id = '3f8e4b83-9ecb-4455-8c04-f9b5f67d1266'; -- Razzmatazz Barcelona
update public.clubs set description_i18n = jsonb_build_object('en', 'Legendary club on Plaça Reial in the Gothic Quarter. A late-night meeting point with electronic music and a cosmopolitan Barcelona crowd.', 'de', 'Legendärer Club an der Plaça Reial im Gotischen Viertel. Nächtlicher Treffpunkt mit elektronischer Musik und kosmopolitischem Publikum.') where id = 'eaca6692-92cf-4d4c-a936-db638a63eba7'; -- Mooem Barcelona
update public.clubs set description_i18n = jsonb_build_object('en', 'Concert venue and club on Plaça Reial. A stage for live music, indie and electronic sets for an alternative Barcelona crowd.', 'de', 'Konzertsaal und Club an der Plaça Reial. Bühne für Live-Musik, Indie und elektronische Sets für ein alternatives Publikum.') where id = 'a0a05dff-3b22-4b20-b79d-953358b54382'; -- Sidecar Factory Club
update public.clubs set description_i18n = jsonb_build_object('en', 'Alternative nightlife club in central Seville. Live music, DJ sessions and an independent, young crowd.', 'de', 'Alternativer Club im Zentrum von Sevilla. Live-Musik, DJ-Sets und ein junges, unabhängiges Publikum.') where id = 'fc3bf3a3-6d24-4279-b993-ddb2d3ef5430'; -- Sala Malandar
update public.clubs set description_i18n = jsonb_build_object('en', 'Historic nightclub on Palma''s seafront promenade. A landmark of Mallorca''s nightlife with several floors and distinct atmospheres.', 'de', 'Historische Diskothek an der Strandpromenade von Palma. Wahrzeichen des mallorquinischen Nachtlebens mit mehreren Etagen und unterschiedlichen Stilen.') where id = '8aa2122b-a2ab-4441-b497-a0d7f8d50cbb'; -- Tito's Palma
update public.clubs set description_i18n = jsonb_build_object('en', 'Concert hall in the historic centre of Seville. An intimate live music venue hosting national and international artists.', 'de', 'Konzertsaal im historischen Zentrum von Sevilla. Intimer Ort für Live-Musik mit nationalen und internationalen Künstlern.') where id = 'a3068a62-9846-4950-8909-9bd1c7d12bba'; -- Antique Teatro Sevilla
update public.clubs set description_i18n = jsonb_build_object('en', 'Club and restaurant on Barceloneta beach with harbour views. An elegant nightlife spot combining Asian cuisine, cocktails and DJ sets.', 'de', 'Club und Restaurant am Strand von Barceloneta mit Hafenblick. Elegante Kombination aus asiatischer Küche, Cocktails und DJ-Sets.') where id = '723e01ec-bb77-4365-bd1b-426cbf7dadd8'; -- Shoko Barcelona
update public.clubs set description_i18n = jsonb_build_object('en', 'Cocktail club on Palma''s seafront promenade overlooking the marina. A festive nightlife spot with varied music for a night out in Palma.', 'de', 'Cocktailclub an der Strandpromenade von Palma mit Blick auf den Yachthafen. Festlicher Ort mit vielseitiger Musik für einen Abend in Palma.') where id = '3d1d0337-27f1-49d4-81e3-6c6c1b688582'; -- Castro's Palma
update public.clubs set description_i18n = jsonb_build_object('en', 'Central Seville nightclub with several dance floors. A festive venue with varied music for a night out in the city.', 'de', 'Zentral gelegene Diskothek in Sevilla mit mehreren Tanzflächen. Festlicher Ort mit vielseitiger Musik für die Nacht in der Stadt.') where id = '9c7b53f7-35e1-4d47-a66e-4b333c7997cd'; -- Discotheque Sevilla
update public.clubs set description_i18n = jsonb_build_object('en', 'Concert hall and club on the left bank of the Nervión in Bilbao. A reference for live music with artists across several genres.', 'de', 'Konzertsaal und Club am linken Nervión-Ufer in Bilbao. Wichtiger Ort für Live-Musik mit Künstlern verschiedenster Genres.') where id = '047a593d-563d-4945-8daf-ac4856881a3e'; -- Kafe Antzokia Bilbao
update public.clubs set description_i18n = jsonb_build_object('en', 'Club specialising in electronic and indie music in Bilbao. A reference of the city''s alternative nightlife scene with a young crowd.', 'de', 'Auf Electronic und Indie spezialisierter Club in Bilbao. Wichtiger Ort der alternativen Nachtleben-Szene mit jungem Publikum.') where id = 'f88739b9-50bf-45eb-8f49-2bcdc35c769d'; -- Surco Bilbao
update public.clubs set description_i18n = jsonb_build_object('en', 'Concert venue and club in Palma''s old town. A stage for live music, indie and alternative acts.', 'de', 'Konzertsaal und Club in der Altstadt von Palma. Bühne für Live-Musik, Indie und alternative Acts.') where id = 'bd7ef6b6-eaa6-45cf-b9ce-bfe767708138'; -- Abraxas Palma
update public.clubs set description_i18n = jsonb_build_object('en', 'Historic Ibiza megaclub holding several thousand people. A pioneer of Balearic electronic music, famous for its foam parties and legendary themed nights.', 'de', 'Historischer Megaclub auf Ibiza mit Platz für mehrere Tausend Gäste. Pionier der balearischen Electronic-Szene, berühmt für Foam Parties und legendäre Themenabende.') where id = '0b4178f8-9da2-4d25-8d65-177698c5504c'; -- Amnesia Ibiza
update public.clubs set description_i18n = jsonb_build_object('en', 'Club with an electronic music and DJ session focus in the Deusto area of Bilbao. A festive nightlife spot for a night out in the city.', 'de', 'Club mit Fokus auf elektronische Musik und DJ-Sets im Stadtteil Deusto in Bilbao. Festlicher Ort für einen Abend in der Stadt.') where id = '02aff3b8-b070-4d74-b884-7c823f73db82'; -- Barceloneta Club Bilbao
